import "./globals.css";
import { Merriweather, Open_Sans } from "next/font/google";
import UserProvider from "@/providers/UserProvider";
import NextProvider from "@/providers/NextProvider";

export const merriweather = Merriweather({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-merriweather",
});

export const openSans = Open_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Oddaj rzeczy by AS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${openSans.variable} font-sans `}>
        <NextProvider>
          <UserProvider>{children}</UserProvider>
        </NextProvider>
      </body>
    </html>
  );
}
